Update workflow-one.yml
fixing issues with the arifacts download

diff --git a/.github/workflows/workflow-one.yml b/.github/workflows/workflow-one.yml
--- a/.github/workflows/workflow-one.yml
+++ b/.github/workflows/workflow-one.yml
@@ -39,9 +39,12 @@ jobs:
       - uses: actions/setup-node@v4
         with:
           node-version: 22
+      - uses: actions/download-artifact@v4
+        with:
+          name: build-artifacts
           
       - name: Test t=file existance
-        run: test -f build/index.html
+        run: test -f build/index.html && echo "File exists" || (echo "File missing"; exit 1)
   
   Unit-Testing:
     needs: Build_the_website
